language: node_js

node_js:
  - node
env:
  global:
    - TZ=Asia/Tokyo
    - GIT_AUTHOR_NAME='JiroTakita'
    - GIT_AUTHOR_EMAIL=takijiro0925@gmail.com
    - GIT_COMMITTER_NAME='JiroTakita'
    - GIT_COMMITTER_EMAIL=takijiro0925@gmail.com

jobs:
  include:
    - script: npm test
    - stage: scrape
      if: type = cron AND branch = master
      script
        - git checkout master
        - npm start
        - npm test
        - openssl aes-256-cbc -K $encrypted_b9d96adb87be_key -iv $encrypted_b9d96adb87be_iv -in deploy-key.enc -out .\\deploy-key -d
        - chmod 600 ~/.ssh/id_rsa
        - ./scripts/push-if-updated.sh ./event/*.json