language: node_js
node_js:
- node
env:
  global:
  - TZ=Asia/Tokyo
  - GIT_AUTHOR_NAME='JiroTakita'
  - GIT_AUTHOR_EMAIL=takijiro0925@gmail.com
  - GIT_COMMITTER_NAME='JiroTakita'
  - GIT_COMMITTER_EMAIL=takijiro0925@gmail.com
jobs:
  include:
  - script: npm test
  - stage: scrape
    if: type = cron AND branch = master
    script:
    - git checkout master
    - npm start
    - npm test
    - openssl aes-256-cbc -K $encrypted_97fdd94136a3_key -iv $encrypted_97fdd94136a3_iv -in enc_key.enc -out .\\enc_key -d
    - chmod 600 ~/.\\enc_key
    - "./scripts/push-if-updated.sh ./event/*.json"
