# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: '0 13 */3 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm start
    - name: git setting
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        git config --local user.email "takijiro0925@gmail.com"
        git config --local user.name "JiroTakita"
    - uses: actions/checkout@v2
    - name: Push auto-fixed files
      run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "fixed auto-fixable textlint errors by github-actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


